// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswiBnf5l52yzrMxwJK9kT6OwjWR1_U-o',
    appId: '1:1009668375259:web:bbeec2f5c7c89af1ecc2fe',
    messagingSenderId: '1009668375259',
    projectId: 'fir-flutter-codelab-d3eaf',
    authDomain: 'fir-flutter-codelab-d3eaf.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d3eaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuP_Tjl3ZSjYmKoDXPSkM7CIAbuyzRwCY',
    appId: '1:1009668375259:android:c5d21d7807dafe74ecc2fe',
    messagingSenderId: '1009668375259',
    projectId: 'fir-flutter-codelab-d3eaf',
    storageBucket: 'fir-flutter-codelab-d3eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwEx_5ltC4iDXn4_Ta7jTod0R-iQcS4c',
    appId: '1:1009668375259:ios:a8d561bcbc01ce4cecc2fe',
    messagingSenderId: '1009668375259',
    projectId: 'fir-flutter-codelab-d3eaf',
    storageBucket: 'fir-flutter-codelab-d3eaf.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVwEx_5ltC4iDXn4_Ta7jTod0R-iQcS4c',
    appId: '1:1009668375259:ios:a8d561bcbc01ce4cecc2fe',
    messagingSenderId: '1009668375259',
    projectId: 'fir-flutter-codelab-d3eaf',
    storageBucket: 'fir-flutter-codelab-d3eaf.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}